#pragma config(Sensor, in1, lightSensor, sensorReflection)
#pragma config(Sensor, in2, potent, sensorPotentiometer)
#pragma config(Sensor, dgtl11, bump1, sensorNone)
#pragma config(Sensor, dgtl12, bump2, sensorNone)
#pragma config(Motor, port2, leftMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor, port3, rightMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor, port4, Servo, tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard !!*//

/************************************************************
 *
 *  This file is meant as an introduction and as a template for developing
 *  programs to run on the Vex controller.
 *
 *************************************************************/

/************************************************************
 *
 *	main
 *
 *************************************************************/
void ServoMove(int servoPosition);
bool doServo = true;

void turn(int degree) {
    writeDebugStreamLine("Degree Value: %d", degree);
    degree -= 90;
    int speed = 50;
    if (degree < 0)
        speed = -50;
    
    motor[leftMotor] = 0 - speed; //fullspeed backwards
    motor[rightMotor] = speed; //fullspeed backwards
    wait1Msec(5 * abs(degree));  // keep backing up for 1000ms (1 sec)
    writeDebugStreamLine("Turn Value: %d, Speed: %d", 5 * abs(degree), speed);
}

task main() {
    //  int bumper = 1;
    // normal bumper state = 1; when pressed = 0
    int lightValue;
    int speed;
    int brightest = 1000;
    int pos = 0;
    float potentPos = 0.0;
    wait1Msec(2000);
    // give stuff time to turn on
    
    ClearTimer(T1); //Resets the value of Timer "T1" back to zero seconds.
    int valTime100; //Create three integers to read the value of the timer.
    
    while(true) {
        // update timer
        valTime100 = time100[T1];
        //Gets the value of Timer T1 in 100ms increments and stores it in a variable.
        
        // 1, read value of the light sensor
        lightValue = SensorValue[lightSensor];
        speed = (1000 - lightValue) / 10;
        
        //Joystick control of the motors
        motor[leftMotor]   =  50;       // up = CW
        motor[rightMotor]  =  50;       // up = CCW
        
        if(doServo) {
            motor[leftMotor]   =  0;       // up = CW
            motor[rightMotor]  =  0;       // up = CCW
            brightest = 1000;
            for (int i = -127; i<127 ; i += 5) {
                ServoMove(i);
                lightValue = SensorValue[lightSensor];
                if(lightValue < brightest) {
                    brightest = lightValue;
                    pos = i;
                }
            }
            doServo = false;
            ServoMove(pos);
            wait1Msec(500);
            turn(SensorValue(potent) / 15);
            ClearTimer(T1);
        }
        
        //writeDebugStreamLine("Angle Value: %d", SensorValue(potent) / 15);
        if(valTime100 >= 20) {
            doServo = true;
            ClearTimer(T1);
        }
    }
}

void ServoMove(int servoPosition) {
    //writeDebugStreamLine("Servo Position = %d",servoPosition);
    motor[Servo] = servoPosition;
    wait1Msec(100);
}
