#pragma config(Sensor, in1, lightSensor, sensorReflection)
#pragma config(Sensor, dgtl11, bump1, sensorNone)
#pragma config(Sensor, dgtl12, bump2, sensorNone)
#pragma config(Motor, port2, leftMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor, port3, rightMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor, port4, Servo, tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard !!*//

/***********************************************************
 *
 *  This file is meant as an introduction and as a template for developing
 *  programs to run on the Vex controller.
 *
 ***********************************************************/

/***********************************************************
 *
 *	main
 *
 ***********************************************************/
void ServoMove(int servoPosition);
bool doServo = true;

task main() {
    //  int bumper = 1;
    // normal bumper state = 1; when pressed = 0
    int lightValue;
    int speed;
    int brightest = 1000;
    int pos = 0;
    wait1Msec(2000);
    // give stuff time to turn on
    
    while(true) {
        // 1, read value of the light sensor
        lightValue = SensorValue[lightSensor];
        speed = (1000 - lightValue) / 10;
        writeDebugStreamLine("%d", lightValue);
        
        //Joystick control of the motors
        motor[leftMotor]   =  0;       // up = CW
        motor[rightMotor]  =  0;       // up = CCW
        
        
        if(doServo) {
            for (int i = -127; i<127 ; i +=1) {
                ServoMove(i);
                lightValue = SensorValue[lightSensor];
                if(lightValue < brightest) {
                    brightest = lightValue;
                    pos = i;
                }
            }
            doServo = false;
        }
        ServoMove(pos);
    }
}

void ServoMove(int servoPosition) {
    writeDebugStreamLine("Servo Position = %d",servoPosition);
    motor[Servo] = servoPosition;
    wait1Msec(50);
}
