#pragma config(Sensor, dgtl1,   leftTouch,      sensorNone)
#pragma config(Sensor, dgtl2,   rightTouch,     sensorNone)
#pragma config(Sensor, dgtl5,   sonar,          sensorSONAR_cm)
#pragma config(Sensor, dgtl11,  bump1,          sensorNone)
#pragma config(Sensor, dgtl12,  bump2,          sensorNone)
#pragma config(Motor,  port2,   leftMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,   rightMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard!!*//

/**********************************************************
 *
 *  This file is meant as an introduction and as a template for
 *  developing programs to run on the Vex controller.
 *
 **********************************************************/

/**********************************************************
 *
 *	main
 *
 **********************************************************/
void ServoMove(int servoPosition);
int sonarValue;
bool leftTurned = false;
bool rightTurned = false;

void turn(int degree) {
    int speed = 100;
    if (degree < 0)
        speed = -100;
    
    motor[leftMotor] = -speed;
    // if degree is negative, left goes backward
    motor[rightMotor] = speed;
    // and right goes forward to turn
    wait1Msec(2.6 * abs(degree));
}

task main() {
    int leftSide;
    wait1Msec(2000);
    
    //Resets the value of Timer "T1" back to zero seconds.
    ClearTimer(T1);
    ClearTimer(T2);
    //Create three integers to read the value of the timer.
    int valTime10;
    int valTimeRight10;
    
    while(true) {
        // update timer
        valTime10 = time10[T1];
        //Gets the value of Timer T1 in 100ms increments and stores it in a variable.
        if (valTime10 >= 100) {
            leftTurned = false;
            ClearTimer(T1);
        }
        valTimeRight10 = time10[T2];
        if (valTimeRight10 >= 300) {
            rightTurned = false;
            ClearTimer(T2);
        }
        
        // Initial Speed
        motor[leftMotor]   =  50;       // up = CW
        motor[rightMotor]  =  50;       // up = CCW
        
        leftSide = SensorValue[sonar];
        
        if(leftSide > 70 && !(leftTurned || rightTurned)) {
            motor[leftMotor]   =  0;       // up = CW
            motor[rightMotor]  =  0;
            wait1Msec(300);
            turn(-90);
            ClearTimer(T1);
            leftTurned = true;
        }
        
        //If the bumper is press, automatically backup
        while(!SensorValue[bump1] || !SensorValue[bump2]) {
            writeDebugStreamLine("bumper is hit");
            
            motor[leftMotor] = -50;
            motor[rightMotor] = -50;
            wait1Msec(200);
            
            motor[leftMotor]  = 0;  //stop motors
            motor[rightMotor] = 0;  //stop motors
            wait1Msec(200);
            
            turn(90);
            
            motor[leftMotor]  = 0;  //stop motors
            motor[rightMotor] = 0;  //stop motors
            wait1Msec(200);
            
            rightTurned = true;
        }
        
        while(!SensorValue[leftTouch])
            turn(-1);
        
        while(!SensorValue[rightTouch])
            turn(1);
    }
}

void ServoMove(int servoPosition){
    motor[Servo] = servoPosition;
    wait1Msec(100);
}
